#!/bin/sh
set -eu

pattern=""
for arg in "$@"; do
  case "$arg" in
    -*) ;;
    *) pattern="$arg" ;;
  esac
done

case "$pattern" in
  gptokeyb|gptokeyb2|*gptokeyb*)
    exec "${PLUMOS_ROOT:-/mnt/plumos}/bin/plumos-portmaster-gptokeyb-stop" stop
    ;;
  *)
    printf 'plumOS PortMaster: denied unowned pkill pattern: %s\n' "$pattern" >&2
    exit 1
    ;;
esac
